//
//  upnpx.h
//  upnpx
//
//  Created by Sean Siefert on 1/14/16.
//  Copyright © 2016 Bruno Keymolen. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for upnpx.
FOUNDATION_EXPORT double upnpxVersionNumber;

//! Project version string for upnpx.
FOUNDATION_EXPORT const unsigned char upnpxVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <upnpx/PublicHeader.h>

#import "MediaRenderer1Device.h"
#import "DeviceFactory.h"
#import "iphoneport.h"
#import "LastChangeParser.h"
#import "UPnPEvents.h"
#import "UPnPEventParser.h"
#import "BasicParser.h"
#import "BasicHTTPServer_ObjC.h"
#import "SoapAction.h"
#import "StateVariable.h"
#import "BasicUPnPDevice.h"
#import "BasicUPnPService.h"
#import "upnpx.h"
#import "UPnPManager.h"
#import "upnp.h"
#import "SSDPDB_ObjC.h"
#import "SoapActionsLayer3Forwarding1.h"
#import "StateVariableRange.h"
#import "osal.h"
#import "SoapActionsDeviceProtection1.h"
#import "SoapActionsSwitchPower1.h"
#import "basichttpserver.h"
#import "ssdpnotifybye.h"
#import "DigitalSecurityCamera1Device.h"
#import "LAN1Device.h"
#import "SoapActionsWANIPConnection1.h"
#import "BasicDeviceParser.h"
#import "SoapActionsInputConfig1.h"
#import "WAN2Device.h"
#import "ssdpdbobserver.h"
#import "ssdpdb.h"
#import "OrderedDictionary.h"
#import "MediaServer1BasicObject.h"
#import "MediaServer1ContainerObject.h"
#import "httpsession.h"
#import "StateVariableList.h"
#import "SoapActionsAVTransport1.h"
#import "SoapActionsWANDSLLinkConfig1.h"
#import "ssdpsearchreq.h"
#import "SoapActionsLANHostConfigManagement1.h"
#import "SoapActionsCallManagement1.h"
#import "TelephonyClient1Device.h"
#import "SoapActionsDigitalSecurityCameraSettings1.h"
#import "ssdptools.h"
#import "SoapActionsConnectionManager1.h"
#import "MediaServer1Device.h"
#import "SoapActionsWANIPConnection2.h"
#import "SoapActionsDigitalSecurityCameraMotionImage1.h"
#import "ssdpdbdevice.h"
#import "SocketServer_ObjC.h"
#import "SoapActionsConfigurationManagement1.h"
#import "SoapActionsRendering.h"
#import "TelephonyServer1Device.h"
#import "ssdpmessage.h"
#import "SoapActionsRenderingControl1.h"
#import "SoapActionsWANIPv6FirewallControl1.h"
#import "socketserverconnection.h"
#import "ssdpobserver.h"
#import "ssdpparser.h"
#import "SoapActionsDigitalSecurityCameraStillImage1.h"
#import "MediaPlaylist.h"
#import "SoapActionsWANCableLinkConfig1.h"
#import "MediaServerBasicObjectParser.h"
#import "WANConnection2Device.h"
#import "SoapActionsMessaging1.h"
#import "SoapActionsWANEthernetLinkConfig1.h"
#import "BinaryLight1Device.h"
#import "ssdp.h"
#import "BasicServiceParser.h"
#import "DimmableLight1Device.h"
#import "SoapActionsWANPOTSLinkConfig1.h"
#import "SoapActionsMediaManagement1.h"
#import "SoapActionsWANCommonInterfaceConfig1.h"
#import "ssdpnotifyupdate.h"
#import "ssdphttp.h"
#import "SoapActionsContentDirectory1.h"
#import "MediaServer1ItemObject.h"
#import "BasicParserAsset.h"
#import "socketServerobserver.h"
#import "socketserver.h"
#import "ssdpsearchresp.h"
#import "tools.h"
#import "ssdpnotifyalive.h"
#import "SoapActionsWANPPPConnection1.h"
#import "MediaServer1ItemRes.h"
#import "ssdpnotify.h"
#import "SoapActionsDimming1.h"
#import "WANConnection1Device.h"
#import "basichttpobserver.h"
#import "NSString+UPnPExtentions.h"
#import "ssdpmsearch.h"
#import "InternetGateway2Device.h"
#import "UPnPDB.h"